services:
  - type: web
    name: platform_crane
    env: python
    buildCommand: "pipenv lock --requirements > requirements.txt　&& pip install -r requirements.txt"
    startCommand: gunicorn app:app
    plan: free
